In [1]:
import numpy as np
a = np.arange(16)
a.shape=(4,4)

In [19]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
res = []
for i in range(0,a.shape[1],2):
    for j in range(0,a.shape[0],2): 
        res.append(a[i:i+2,j:j+2])
print(res)

[array([[0, 1],
       [4, 5]]), array([[2, 3],
       [6, 7]]), array([[ 8,  9],
       [12, 13]]), array([[10, 11],
       [14, 15]])]


In [2]:
np.log2(2)

1.0

In [3]:
np.abs(-1)

1

In [13]:
s = ''
s = s+''.join(bin(22)[2:])
print(s)

TypeError: bad operand type for unary ~: 'str'

In [14]:
dc_table = ["00","010", "011","100","101","110","1110","11110","111110","1111110","11111110","111111110"]#DC熵编码符号1（尺寸）对应的表
dc_table[1]

'010'

In [15]:
int(3.6)

3

In [24]:
def z_scan(ac_matrix)->list:
    '''
    args:
        8x8-1 ac component_matrix
    return:
        63 array
    '''
    res = []
    pot_x=[0,1,2,1,0,0,1,2,3,4,3,2,1,0,0,1,2,3,4,5,6,5,4,3,2,1,0,0,1,2,3,4,5,6,7,7,6,5,4,3,2,1,2,3,4,5,6,7,7,6,5,4,3,4,5,6,7,7,6,5,6,7,7]#扫描的横坐标值
    pot_y=[1,0,0,1,2,3,2,1,0,0,1,2,3,4,5,4,3,2,1,0,0,1,2,3,4,5,6,7,6,5,4,3,2,1,0,1,2,3,4,5,6,7,7,6,5,4,3,2,3,4,5,6,7,7,6,5,4,5,6,7,7,6,7]#扫描的纵坐标值
    
    for i in range(len(pot_x)):
        res.append(ac_matrix[pot_x[i]][pot_y[i]])
    return res

In [26]:
a = np.arange(64)
a.shape=(8,8)
print(a)
print(z_scan(a))
# a[1][1]

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
[1, 8, 16, 9, 2, 3, 10, 17, 24, 32, 25, 18, 11, 4, 5, 12, 19, 26, 33, 40, 48, 41, 34, 27, 20, 13, 6, 7, 14, 21, 28, 35, 42, 49, 56, 57, 50, 43, 36, 29, 22, 15, 23, 30, 37, 44, 51, 58, 59, 52, 45, 38, 31, 39, 46, 53, 60, 61, 54, 47, 55, 62, 63]


In [29]:
np.sqrt(65536)

256.0

In [31]:
'11111'.encode()

b'11111'

In [33]:
263850/8/1024

32.208251953125

In [46]:
a = b'11111'
print(a)
b = bin(int(a,2))
print(b)

b'11111'
0b11111


In [4]:
import cv2
image = cv2.imread('../data/2.png')
print(image.shape)
image = cv2.copyMakeBorder(image, (8-image.shape[0]%8), 0, (8-image.shape[1]%8),0, cv2.BORDER_CONSTANT, value=(128,128,128))


(256, 256, 3)


In [9]:
a = hex(2222)[2:].rjust(4,'0')
print(a)

08ae


In [11]:
for i in (('a','b','c')):
    print(i)

a
b
c


In [12]:
int("111")

111

In [14]:
res = '10101'
res_list = [int(i)for i in res]
print(res_list)

[1, 0, 1, 0, 1]


In [20]:
import numpy as np

amplitude = 2
bin(np.abs(amplitude))[2:]

'10'

In [26]:
a = [1,1]
b = "".join(map(lambda x:str(x), a))
print(b)

11


In [4]:
from encode import *
for i in range(10):
    print(dc_encode(-117,pre_component=-127,lu=2+1))

[1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 